# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'linda' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for linda
  pod 'RNMobileCenter', :podspec => 'https://mobilecentersdkdev.blob.core.windows.net/sdk/MobileCenter-ReactNative.podspec'
  pod 'MobileCenter', :podspec => 'https://mobilecentersdkdev.blob.core.windows.net/sdk/MobileCenter.podspec'

  target 'lindaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
